void Setup_Alarm_Time(void);
void Increase_Alarm_Time(void);
void Decrease_Alarm_Time(void);
void Go_Next_Alarm_Field(void);
void Go_Prev_Alarm_Field(void);
void Exit_Setup_Alarm_Time(void);
void Do_Save_New_Alarm_Time(void);
void Initialize_Setup_Alarm_Time_Screen(void);
void Update_Setup_Alarm_Time_Screen(void);
